// <auto-generated />
using Emprestimos01.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Emprestimos01.Migrations
{
    [DbContext(typeof(Emprestimos01Context))]
    partial class Emprestimos01ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Emprestimos01.Models.Emprestimos", b =>
                {
                    b.Property<int>("EmprestimoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("valorEntrada")
                        .HasColumnType("float");

                    b.Property<double>("valorSolicitado")
                        .HasColumnType("float");

                    b.HasKey("EmprestimoId");

                    b.ToTable("Emprestimos");
                });
#pragma warning restore 612, 618
        }
    }
}
